import { accessScreens } from "@roadcore/auth";
import Link from "next/link";

export default async function AdminHomePage({ params }: { params: Promise<{ tenant: string }> }) {
  const { tenant } = await params;
  const modules = accessScreens.filter((screen) => screen.surface === "admin" && screen.id !== "admin-overview");
  return <main className="p-5 sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Visão geral</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Bom dia, administrador.</h1><p className="mt-2 text-sm text-muted">Acompanhe a empresa e acesse todos os módulos e cadastros.</p></div><Link href={`/${tenant}/admin/commercial/leads/new`} className="rounded-xl bg-primary px-5 py-3 text-sm font-bold text-white">+ Nova oportunidade</Link></div>
    <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Oportunidades ativas","18","5 novas hoje"],["Veículos em estoque","24","19 publicados"],["Negócios no mês","R$ 482 mil","+12,4%"],["Pendências","7","3 requerem atenção"]].map(([label,value,note]) => <article key={label} className="panel p-5"><p className="text-sm text-muted">{label}</p><p className="mt-3 text-2xl font-semibold">{value}</p><p className="mt-2 text-xs text-primary">{note}</p></article>)}</section>
    <section className="mt-8"><div><h2 className="text-xl font-semibold">Módulos e cadastros</h2><p className="mt-1 text-sm text-muted">O perfil Administrador possui acesso completo às áreas abaixo.</p></div><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{modules.map((screen, index) => <Link key={screen.id} href={`/${tenant}${screen.path}`} className="group rounded-2xl border bg-white p-5 transition hover:-translate-y-0.5 hover:border-primary hover:shadow-lg"><div className="flex items-start justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary-50 text-xs font-black text-primary">0{index + 1}</span><span className="text-muted transition group-hover:translate-x-1 group-hover:text-primary">→</span></div><h3 className="mt-6 font-semibold group-hover:text-primary">{screen.name}</h3><p className="mt-2 text-sm leading-6 text-muted">{screen.description}</p></Link>)}</div></section>
  </main>;
}
