import Image from "next/image";
import Link from "next/link";

export default async function AboutPage({params}:{params:Promise<{tenant:string}>}){
  const {tenant}=await params;
  return <main className="flex-1 bg-white">
    <section className="overflow-hidden bg-[#111112] text-white"><div className="page-shell grid min-h-[700px] items-center gap-14 py-16 lg:grid-cols-[.85fr_1.15fr] lg:py-24"><div><Image src="/tenants/fogueiracaminhoes/about/logo-heritage.svg" alt="Fogueira Caminhões" width={390} height={96} className="h-auto w-full max-w-[360px]"/><p className="mt-8 text-xs font-bold uppercase tracking-[.2em] text-primary-400">Tradição em atendimento de qualidade</p><h1 className="mt-5 text-balance text-5xl font-semibold leading-[1.02] tracking-[-.05em] sm:text-6xl">Gente que entende de caminhão e valoriza cada cliente.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-neutral-400">Contate-nos e confira nossos veículos, máquinas e caminhões selecionados para o seu próximo negócio.</p><div className="mt-9 flex flex-wrap gap-3"><Link href={`/${tenant}/catalog`} className="inline-flex min-h-12 items-center rounded-xl bg-primary px-6 py-3 text-sm font-bold text-white">Conferir veículos →</Link><Link href={`/${tenant}/contact`} className="inline-flex min-h-12 items-center rounded-xl border border-white/20 px-6 py-3 text-sm font-bold">Contate-nos</Link></div></div><div className="relative"><div className="absolute -inset-8 rounded-full bg-primary/15 blur-3xl"/><div className="relative overflow-hidden rounded-[30px] border border-white/10 bg-neutral-900 p-2 shadow-2xl"><div className="relative aspect-[16/10] overflow-hidden rounded-[24px]"><Image src="/tenants/fogueiracaminhoes/about/team.jpg" alt="Fachada e pátio da Fogueira Caminhões" fill priority sizes="(max-width:1024px) 100vw, 60vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent"/><div className="absolute inset-x-0 bottom-0 flex items-end justify-between p-6"><div><p className="text-xs text-neutral-300">Nossa casa</p><p className="mt-1 font-semibold">Itapeva · Minas Gerais</p></div><span className="rounded-full bg-white/10 px-3 py-1.5 text-[10px] backdrop-blur">Compra · Venda · Troca</span></div></div></div><div className="absolute -bottom-6 -left-6 hidden rounded-2xl bg-white p-5 text-[#171717] shadow-xl sm:block"><strong className="text-3xl tracking-tight">18 anos</strong><p className="mt-1 text-xs text-muted">de tradição e confiança</p></div></div></div></section>

    <section className="page-shell py-20 sm:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Nossa história</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em]">Quem conhece a estrada entende o valor da palavra.</h2></div><div className="space-y-5 text-lg leading-8 text-muted"><p>A Fogueira Caminhões nasceu do contato direto com quem trabalha, produz e transporta. Aprendemos que um bom negócio começa muito antes da chave mudar de mão: começa com informação clara e confiança.</p><p>Selecionamos caminhões usados e seminovos, ajudamos na compra, venda e troca, e acompanhamos cada cliente durante todo o processo documental e financeiro.</p><p className="font-medium text-foreground">Nosso compromisso é simples: falar a verdade, conhecer o produto e estar disponível quando o cliente precisar.</p></div></div></section>

    <section className="border-y bg-surface"><div className="page-shell grid grid-cols-2 py-12 sm:grid-cols-4">{[["18","anos de mercado"],["1.200+","negócios realizados"],["26","estados atendidos"],["4,9/5","avaliação dos clientes"]].map(([a,b],i)=><div key={b} className={`px-4 py-4 ${i?"sm:border-l":""}`}><strong className="text-3xl tracking-tight text-primary">{a}</strong><p className="mt-2 text-xs text-muted">{b}</p></div>)}</div></section>

    <section className="page-shell py-20 sm:py-28"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Nosso jeito de trabalhar</p><h2 className="mt-3 text-4xl font-semibold tracking-tight">Valores que aparecem na prática.</h2><p className="mt-5 leading-7 text-muted">Não são palavras na parede. São critérios usados em cada avaliação e negociação.</p></div><div className="grid gap-5 sm:grid-cols-2">{[["Transparência","Informação clara sobre veículo, condição e documentação."],["Conhecimento","Experiência para avaliar configuração, uso e valor de mercado."],["Proximidade","Atendimento direto, humano e sem respostas automáticas."],["Responsabilidade","Cuidado com cada etapa até a conclusão do negócio."]].map(([a,b],i)=><article key={a} className="panel p-7"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary-50 text-xs font-bold text-primary">0{i+1}</span><h3 className="mt-7 text-lg font-semibold">{a}</h3><p className="mt-3 text-sm leading-6 text-muted">{b}</p></article>)}</div></div></section>

    <section className="bg-[#111112] text-white"><div className="page-shell py-20"><div className="grid gap-8 md:grid-cols-3">{[["2008","O início","A Fogueira começa atendendo clientes e transportadores da região."],["2018","Novos caminhos","A rede de compradores e parceiros alcança diferentes estados."],["Hoje","Presença nacional","Estoque digital, atendimento próximo e negócios em todo o Brasil."]].map(([year,title,copy])=><article key={year} className="border-t border-white/15 pt-6"><span className="text-sm font-bold text-primary-400">{year}</span><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-neutral-500">{copy}</p></article>)}</div></div></section>

    <section className="page-shell py-20 text-center sm:py-24"><p className="eyebrow">Venha nos conhecer</p><h2 className="mt-4 text-balance text-4xl font-semibold tracking-[-.04em] sm:text-5xl">O próximo negócio pode começar com uma conversa.</h2><p className="mx-auto mt-5 max-w-xl leading-7 text-muted">Visite nosso pátio ou fale com a equipe para encontrar, vender ou trocar seu caminhão.</p><Link href={`/${tenant}/contact`} className="mt-8 inline-flex rounded-xl bg-primary px-6 py-3 text-sm font-bold text-white">Falar com a Fogueira →</Link></section>
  </main>;
}
