import Link from "next/link";

export default async function ConsignmentPage({ params }: { params: Promise<{ tenant: string }> }) {
  const { tenant } = await params;
  return <main className="flex-1">
    <section className="overflow-hidden bg-[#111112] text-white"><div className="page-shell py-20 lg:py-28"><p className="text-xs font-bold uppercase tracking-[.2em] text-primary-400">Venda em consignação</p><h1 className="mt-5 max-w-4xl text-balance text-5xl font-semibold tracking-[-.05em] sm:text-6xl">Seu caminhão anunciado com apresentação e negociação profissionais.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-neutral-400">Cuidamos da divulgação, qualificação dos interessados e condução das propostas para você vender com mais tranquilidade.</p><div className="mt-9 flex flex-wrap gap-3"><Link href={`/${tenant}/sell`} className="rounded-xl bg-primary px-6 py-3 text-sm font-bold text-white">Quero consignar →</Link><Link href={`/${tenant}/contact`} className="rounded-xl border border-white/20 px-6 py-3 text-sm font-bold">Falar com a equipe</Link></div></div></section>
    <section className="page-shell py-20"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">Uma venda melhor conduzida</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.04em]">Você mantém o controle. Nós movimentamos o negócio.</h2><p className="mt-5 leading-7 text-muted">A estratégia é definida em conjunto, com condições transparentes e acompanhamento durante todas as etapas.</p></div><div className="grid gap-4 sm:grid-cols-2">{[["Anúncio profissional","Fotos, descrição técnica e posicionamento do veículo."],["Audiência qualificada","Divulgação para compradores do setor de pesados."],["Triagem de contatos","Conversas e propostas organizadas pela nossa equipe."],["Apoio na conclusão","Orientação documental até o fechamento do negócio."]].map(([a,b])=><article key={a} className="rounded-2xl border bg-white p-6"><h3 className="font-semibold">{a}</h3><p className="mt-3 text-sm leading-6 text-muted">{b}</p></article>)}</div></div></section>
    <section className="bg-primary text-white"><div className="page-shell flex flex-col items-start justify-between gap-6 py-14 md:flex-row md:items-center"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-white/60">Comece pela avaliação</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Vamos preparar seu veículo para o mercado.</h2></div><Link href={`/${tenant}/sell`} className="shrink-0 rounded-xl bg-white px-6 py-3 text-sm font-bold text-primary">Enviar dados do veículo →</Link></div></section>
  </main>;
}
