import type { VehicleListing } from "./components/vehicle-card";

export const sampleListings: VehicleListing[] = [
  {
    id: "vw-8-150-e-worker",
    title: "Volkswagen 8-150 E Worker",
    priceInCents: null,
    location: "Itapeva, SP",
    status: "available",
    year: "2004",
    imageSrc: "/tenants/fogueiracaminhoes/vehicles/vw-8-150-e-worker/01.jpg",
    gallery: ["01.jpg","02.jpg","03.jpg","04.jpg","05.jpg"].map(file => `/tenants/fogueiracaminhoes/vehicles/vw-8-150-e-worker/${file}`),
    specs: [["Ano","2004"],["Carroceria","5,30 m"],["Motor","MWM X10"],["Aspiração","Turbo Intercooler"],["Direção","Hidráulica"],["Pneus","Sem câmara"]],
    features: ["Mecânica revisada","Motor MWM X10","Turbinado e com intercooler","Direção hidráulica","Climatizador","Pneus sem câmara"],
    description: "Volkswagen 8-150 E Worker ano 2004, equipado com motor MWM X10, turbo e intercooler. Possui carroceria de 5,30 metros, direção hidráulica, climatizador e mecânica revisada.",
  },
  {
    id: "mercedes-l-1218-el",
    title: "Mercedes-Benz L 1218 EL",
    priceInCents: null,
    location: "Itapeva, SP",
    status: "available",
    year: "2004",
    mileage: "424.967 km",
    imageSrc: "/tenants/fogueiracaminhoes/vehicles/mercedes-l-1218-el/01.jpg",
    gallery: ["01.jpg","02.jpg","03.jpg","04.jpg","05.jpg"].map(file => `/tenants/fogueiracaminhoes/vehicles/mercedes-l-1218-el/${file}`),
    specs: [["Ano","2004"],["Quilometragem","424.967 km"],["Câmbio","5 marchas"],["Motor","4 cilindros"],["Carroceria","Nova · 6,50 m"],["Pneus","Sem câmara · medida 275"]],
    features: ["Carroceria nova com 6,50 m","2 pneus novos na dianteira","4 pneus recapados na tração","Pneus sem câmara medida 275","Câmbio de 5 marchas","Sinistro informado no histórico"],
    historyStatus: "reported",
    historyNotice: "Com sinistro informado",
    description: "Caminhão com carroceria nova de 6,50 metros, motor de 4 cilindros e câmbio de 5 marchas. O veículo possui registro de sinistro, condição informada de forma transparente e sujeita à conferência documental antes da negociação.",
  },
  {
    id: "ford-cargo-2428e",
    title: "Ford Cargo 2428e 6x2",
    priceInCents: null,
    location: "Itapeva, MG",
    status: "available",
    year: "Consulte o ano",
    mileage: "647.000 km",
    imageSrc: "/tenants/fogueiracaminhoes/vehicles/ford-cargo-2428e/01.jpg",
    gallery: ["01.jpg","02.jpg","03.jpg","04.jpg","05.jpg","06.jpg"].map(file => `/tenants/fogueiracaminhoes/vehicles/ford-cargo-2428e/${file}`),
    specs: [["Configuração","6x2"],["Quilometragem","647.000 km"],["Câmbio","6 marchas reduzido"],["Carroceria","Grade baixa reformada"],["Pneus","Sem câmara"],["Procedência","Único dono"]],
    features: ["Carroceria grade baixa reformada","Pneus sem câmara","Molejo reforçado","Interna em bom estado","Único dono","Manual e segunda chave"],
  },
  {
    id: "mercedes-atego-2425",
    title: "Mercedes-Benz Atego 2425",
    priceInCents: 30000000,
    location: "Itapeva, MG",
    status: "available",
    year: "2011",
    mileage: "379.000 km",
    imageSrc: "/tenants/fogueiracaminhoes/vehicles/mercedes-atego-2425/01.jpg",
    gallery: ["01.jpg","02.jpg"].map(file => `/tenants/fogueiracaminhoes/vehicles/mercedes-atego-2425/${file}`),
    specs: [["Configuração","3 eixos"],["Ano","2011"],["Quilometragem","379.000 km originais"],["Câmbio","6 marchas reduzido"],["Implemento","Caçamba Pastre 2011"],["Procedência","Único dono"]],
    features: ["Caminhão todo selado","Caçamba Pastre ano 2011","Quilometragem original","Câmbio reduzido","Único dono","Configuração de 3 eixos"],
  },
  {
    id: "scania-g420",
    title: "Scania G 420 A 6x2",
    priceInCents: 23000000,
    location: "Itapeva, MG",
    status: "available",
    year: "2010/2010",
    mileage: "1.432.000 km",
    imageSrc: "/tenants/fogueiracaminhoes/vehicles/scania-g420/01.jpg",
    gallery: ["01.jpg","02.jpg"].map(file => `/tenants/fogueiracaminhoes/vehicles/scania-g420/${file}`),
    specs: [["Configuração","6x2"],["Ano","2010/2010"],["Quilometragem","1.432.000 km"],["Marca","Scania"],["Modelo","G 420 A"],["Combustível","Diesel"]],
    features: ["Ar-condicionado","Piloto automático","Vidros elétricos","Buzina marítima","Cabine leito","Configuração 6x2"],
  },
  {
    id: "mercedes-1718-poliguindaste",
    title: "Mercedes-Benz 1718 Poliguindaste",
    priceInCents: 17000000,
    location: "Itapeva, MG",
    status: "available",
    year: "2011/2011",
    imageSrc: "/tenants/fogueiracaminhoes/vehicles/mercedes-1718-poliguindaste/01.jpg",
    gallery: ["01.jpg","02.jpg"].map(file => `/tenants/fogueiracaminhoes/vehicles/mercedes-1718-poliguindaste/${file}`),
    specs: [["Ano","2011/2011"],["Implemento","Poliguindaste"],["Câmbio","6 marchas reduzido"],["Freio","Top Brake"],["Pneus","Sem câmara"],["Marca","Mercedes-Benz"]],
    features: ["Poliguindaste","Top Brake","Câmbio reduzido","Pneus sem câmara","Cabine conservada","Pronto para operação"],
  },
  {
    id: "vw-meteor-29520",
    title: "Volkswagen Meteor 29.520 6x4",
    priceInCents: null,
    location: "Itapeva, MG",
    status: "available",
    year: "2021/2022",
    mileage: "396.000 km",
    imageSrc: "/tenants/fogueiracaminhoes/vehicles/vw-meteor-29520/01.jpg",
    gallery: ["01.jpg","02.jpg"].map(file => `/tenants/fogueiracaminhoes/vehicles/vw-meteor-29520/${file}`),
    specs: [["Configuração","6x4"],["Ano","2021/2022"],["Quilometragem","396.000 km"],["Modelo","Meteor 29.520"],["Pneus","Todos sem recap"],["Equipamento","Kit hidráulico"]],
    features: ["Rodas de alumínio","Ar-condicionado","Kit hidráulico","Pneus sem recap","Excelente conservação","Configuração 6x4"],
  },
  {
    id: "scania-p360",
    title: "Scania P 360 A 6x2 E5",
    priceInCents: 29000000,
    location: "Itapeva, MG",
    status: "available",
    year: "2015",
    mileage: "672.000 km",
    imageSrc: "/tenants/fogueiracaminhoes/vehicles/scania-p360/01.jpg",
    gallery: ["01.jpg","02.jpg"].map(file => `/tenants/fogueiracaminhoes/vehicles/scania-p360/${file}`),
    specs: [["Configuração","6x2"],["Ano","2015"],["Quilometragem","672.000 km"],["Câmbio","Automático"],["Suspensão","A ar"],["Preço","Tabela FIPE"]],
    features: ["Câmbio automático","Suspensão a ar","Defletor de ar","Pneus sem recap","Aceita troca","Motorização Euro 5"],
  },
];
