import type { VehicleListing } from "./components/vehicle-card";

export const sampleListings: VehicleListing[] = [
  {
    id: "ford-cargo-2428e",
    title: "Ford Cargo 2428e 6x2",
    priceInCents: null,
    location: "Itapeva, MG",
    status: "available",
    year: "Consulte o ano",
    mileage: "647.000 km",
    imageSrc: "/tenants/fogueiracaminhoes/vehicles/ford-cargo-2428e/01.jpg",
    gallery: ["01.jpg","02.jpg","03.jpg","04.jpg","05.jpg","06.jpg"].map(file => `/tenants/fogueiracaminhoes/vehicles/ford-cargo-2428e/${file}`),
    specs: [["Configuração","6x2"],["Quilometragem","647.000 km"],["Câmbio","6 marchas reduzido"],["Carroceria","Grade baixa reformada"],["Pneus","Sem câmara"],["Procedência","Único dono"]],
    features: ["Carroceria grade baixa reformada","Pneus sem câmara","Molejo reforçado","Interna em bom estado","Único dono","Manual e segunda chave"],
  },
  {
    id: "mercedes-atego-2425",
    title: "Mercedes-Benz Atego 2425",
    priceInCents: 30000000,
    location: "Itapeva, MG",
    status: "available",
    year: "2011",
    mileage: "379.000 km",
    imageSrc: "/tenants/fogueiracaminhoes/vehicles/mercedes-atego-2425/01.jpg",
    gallery: ["01.jpg","02.jpg"].map(file => `/tenants/fogueiracaminhoes/vehicles/mercedes-atego-2425/${file}`),
    specs: [["Configuração","3 eixos"],["Ano","2011"],["Quilometragem","379.000 km originais"],["Câmbio","6 marchas reduzido"],["Implemento","Caçamba Pastre 2011"],["Procedência","Único dono"]],
    features: ["Caminhão todo selado","Caçamba Pastre ano 2011","Quilometragem original","Câmbio reduzido","Único dono","Configuração de 3 eixos"],
  },
  {
    id: "scania-g420",
    title: "Scania G 420 A 6x2",
    priceInCents: 23000000,
    location: "Itapeva, MG",
    status: "available",
    year: "2010/2010",
    mileage: "1.432.000 km",
    imageSrc: "/tenants/fogueiracaminhoes/vehicles/scania-g420/01.jpg",
    gallery: ["01.jpg","02.jpg"].map(file => `/tenants/fogueiracaminhoes/vehicles/scania-g420/${file}`),
    specs: [["Configuração","6x2"],["Ano","2010/2010"],["Quilometragem","1.432.000 km"],["Marca","Scania"],["Modelo","G 420 A"],["Combustível","Diesel"]],
    features: ["Ar-condicionado","Piloto automático","Vidros elétricos","Buzina marítima","Cabine leito","Configuração 6x2"],
  },
  {
    id: "mercedes-1718-poliguindaste",
    title: "Mercedes-Benz 1718 Poliguindaste",
    priceInCents: 17000000,
    location: "Itapeva, MG",
    status: "available",
    year: "2011/2011",
    imageSrc: "/tenants/fogueiracaminhoes/vehicles/mercedes-1718-poliguindaste/01.jpg",
    gallery: ["01.jpg","02.jpg"].map(file => `/tenants/fogueiracaminhoes/vehicles/mercedes-1718-poliguindaste/${file}`),
    specs: [["Ano","2011/2011"],["Implemento","Poliguindaste"],["Câmbio","6 marchas reduzido"],["Freio","Top Brake"],["Pneus","Sem câmara"],["Marca","Mercedes-Benz"]],
    features: ["Poliguindaste","Top Brake","Câmbio reduzido","Pneus sem câmara","Cabine conservada","Pronto para operação"],
  },
  {
    id: "vw-meteor-29520",
    title: "Volkswagen Meteor 29.520 6x4",
    priceInCents: null,
    location: "Itapeva, MG",
    status: "available",
    year: "2021/2022",
    mileage: "396.000 km",
    imageSrc: "/tenants/fogueiracaminhoes/vehicles/vw-meteor-29520/01.jpg",
    gallery: ["01.jpg","02.jpg"].map(file => `/tenants/fogueiracaminhoes/vehicles/vw-meteor-29520/${file}`),
    specs: [["Configuração","6x4"],["Ano","2021/2022"],["Quilometragem","396.000 km"],["Modelo","Meteor 29.520"],["Pneus","Todos sem recap"],["Equipamento","Kit hidráulico"]],
    features: ["Rodas de alumínio","Ar-condicionado","Kit hidráulico","Pneus sem recap","Excelente conservação","Configuração 6x4"],
  },
  {
    id: "scania-p360",
    title: "Scania P 360 A 6x2 E5",
    priceInCents: 29000000,
    location: "Itapeva, MG",
    status: "available",
    year: "2015",
    mileage: "672.000 km",
    imageSrc: "/tenants/fogueiracaminhoes/vehicles/scania-p360/01.jpg",
    gallery: ["01.jpg","02.jpg"].map(file => `/tenants/fogueiracaminhoes/vehicles/scania-p360/${file}`),
    specs: [["Configuração","6x2"],["Ano","2015"],["Quilometragem","672.000 km"],["Câmbio","Automático"],["Suspensão","A ar"],["Preço","Tabela FIPE"]],
    features: ["Câmbio automático","Suspensão a ar","Defletor de ar","Pneus sem recap","Aceita troca","Motorização Euro 5"],
  },
];
