import Image from "next/image";
import Link from "next/link";

import { getTenantTheme } from "@/lib/tenant-theme";

export default async function DriverPortalPage({ params }: { params: Promise<{ tenant: string }> }) {
  const { tenant } = await params;
  const theme = getTenantTheme(tenant);
  return <main className="min-h-screen bg-[#f5f5f6] pb-24"><header className="border-b bg-[#111112] text-white"><div className="page-shell flex h-16 items-center justify-between">{theme.logoSrcDark ? <Image src={theme.logoSrcDark} alt={theme.name} width={175} height={42} className="h-9 w-auto object-contain"/> : <strong>{theme.name}</strong>}<span className="rounded-full bg-primary px-3 py-1 text-[10px] font-bold text-white">Motorista</span></div></header>
    <div className="page-shell max-w-5xl py-8"><p className="text-sm text-muted">Olá, João</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Sua jornada de hoje</h1><section className="mt-7 overflow-hidden rounded-3xl bg-[#171717] p-6 text-white shadow-xl sm:p-8"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-wider text-primary-400">Viagem RC-2048 · Em andamento</p><h2 className="mt-3 text-2xl font-semibold">Curitiba → Itapeva</h2><p className="mt-2 text-sm text-neutral-400">Previsão de entrega hoje, 17:30</p></div><button className="rounded-xl bg-primary px-5 py-3 text-sm font-bold text-white">Abrir viagem →</button></div><div className="mt-7 grid grid-cols-2 gap-4 border-t border-white/10 pt-6 sm:grid-cols-4">{[["Veículo","Volvo FH"],["Placa","ABC1D23"],["Carga","Máquinas"],["Distância","284 km"]].map(([label,value]) => <div key={label}><p className="text-[10px] uppercase text-neutral-500">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>)}</div></section>
      <section className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-5">{[["Checklist","Pendente","driver.checklist.create"],["Despesas","Registrar","driver.expense.create"],["Ocorrência","Informar","driver.incident.create"],["Entrega","Confirmar","driver.delivery.confirm"],["Agenda","Ver próximas","driver.schedule.read"]].map(([title,note,permission]) => <button key={title} title={permission} className="rounded-2xl border bg-white p-5 text-left transition hover:border-primary"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary-50 text-primary">✓</span><h2 className="mt-5 text-sm font-semibold">{title}</h2><p className="mt-1 text-[10px] text-muted">{note}</p></button>)}</section>
      <section className="panel mt-7 p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Próximas atividades</h2><p className="mt-1 text-xs text-muted">Agenda vinculada ao seu perfil</p></div><Link href={`/${tenant}/contact`} className="text-xs font-bold text-primary">Suporte</Link></div><div className="mt-5 divide-y">{[["Checklist de saída","Antes de iniciar a viagem","Pendente"],["Parada programada","Ponta Grossa · 12:30","Programada"],["Comprovante de entrega","Após descarregamento","Aguardando"]].map(([title,detail,status]) => <div key={title} className="flex items-center justify-between gap-4 py-4"><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-muted">{detail}</p></div><span className="text-[10px] font-bold text-primary">{status}</span></div>)}</div></section>
    </div></main>;
}
