export interface AdminSectionDefinition {
  id: string;
  eyebrow: string;
  title: string;
  description: string;
  primaryAction: string;
  stats: Array<[string, string, string]>;
  records: Array<[string, string, string]>;
}

export const adminSections: Record<string, AdminSectionDefinition> = {
  commercial: { id: "commercial", eyebrow: "Relacionamento e vendas", title: "Comercial", description: "Centralize clientes, oportunidades, propostas e o acompanhamento das negociações.", primaryAction: "Nova oportunidade", stats: [["Leads ativos","18","5 novos hoje"],["Em negociação","7","R$ 1,4 mi em propostas"],["Conversão","31%","+4 p.p. no mês"]], records: [["Transportadora Horizonte","Volkswagen Worker","Novo contato"],["Agro Vale Logística","Scania P 360","Proposta enviada"],["Expresso Itapeva","Mercedes Atego","Em negociação"]] },
  inventory: { id: "inventory", eyebrow: "Ativos comerciais", title: "Estoque", description: "Cadastre veículos, organize mídia, revise informações e controle a publicação dos anúncios.", primaryAction: "Cadastrar veículo", stats: [["Em estoque","24","19 publicados"],["Em preparação","3","Fotos pendentes"],["Reservados","2","Aguardando conclusão"]], records: [["VW 8-150 E Worker","Publicado","Atualizado hoje"],["Ford Cargo 2428e","Publicado","6 fotos"],["Mercedes L 1218 EL","Em revisão","Documento pendente"]] },
  finance: { id: "finance", eyebrow: "Controle financeiro", title: "Financeiro", description: "Acompanhe propostas, entradas, aprovações, recebimentos e compromissos do negócio.", primaryAction: "Novo lançamento", stats: [["A receber","R$ 286 mil","Próximos 30 dias"],["Propostas","R$ 740 mil","4 aguardando análise"],["Pendências","3","Requerem aprovação"]], records: [["Proposta RC-1038","R$ 230.000","Em análise"],["Entrada Mercedes Atego","R$ 45.000","Confirmada"],["Comissão venda RC-1034","R$ 8.500","Pendente"]] },
  operations: { id: "operations", eyebrow: "Transporte e execução", title: "Operações", description: "Planeje fretes, viagens, despacho, ocorrências e entregas em andamento.", primaryAction: "Nova operação", stats: [["Em andamento","8","3 entregas hoje"],["A despachar","4","2 alta prioridade"],["Ocorrências","1","Em tratamento"]], records: [["RC-2048 · Curitiba → Itapeva","Em trânsito","Previsão 17:30"],["RC-2049 · Sorocaba → Campinas","Carregando","Motorista confirmado"],["RC-2050 · Itapeva → Santos","Planejada","Aguardando veículo"]] },
  fleet: { id: "fleet", eyebrow: "Recursos operacionais", title: "Frota e motoristas", description: "Gerencie veículos operacionais, motoristas, documentos, disponibilidade e bloqueios.", primaryAction: "Novo cadastro", stats: [["Veículos","16","12 disponíveis"],["Motoristas","21","18 ativos"],["Documentos","5","Vencem em 30 dias"]], records: [["Rafael Souza","Disponível","CNH em dia"],["Volvo FH · ABC1D23","Em viagem","Retorno amanhã"],["Scania R · EFG4H56","Bloqueado","Manutenção"]] },
  maintenance: { id: "maintenance", eyebrow: "Disponibilidade e segurança", title: "Manutenção", description: "Controle ordens de serviço, planos preventivos, inspeções e custos técnicos.", primaryAction: "Nova ordem de serviço", stats: [["Ordens abertas","6","2 críticas"],["Preventivas","4","Próximos 15 dias"],["Indisponíveis","2","12% da frota"]], records: [["OS-438 · Scania R","Em execução","Sistema de freios"],["OS-439 · Volvo FH","Agendada","Troca de óleo"],["OS-440 · Carreta SR","Aguardando peça","Suspensão"]] },
  reports: { id: "reports", eyebrow: "Análise e decisão", title: "Relatórios", description: "Consulte indicadores comerciais, operacionais, financeiros e de desempenho da frota.", primaryAction: "Gerar relatório", stats: [["Receita no mês","R$ 482 mil","+12,4%"],["Margem média","18,6%","+2,1 p.p."],["Disponibilidade","88%","Meta 92%"]], records: [["Desempenho comercial","Atualizado hoje","Exportação disponível"],["Custo por veículo","Atualizado ontem","16 veículos"],["Resultado financeiro","Fechamento jul/26","Aprovado"]] },
  users: { id: "users", eyebrow: "Identidades e RBAC", title: "Usuários e acessos", description: "Convide pessoas, atribua perfis, limite filiais e acompanhe o estado dos acessos.", primaryAction: "Convidar usuário", stats: [["Usuários","18","16 ativos"],["Convites","2","Aguardando aceite"],["Perfis","9","Modelos configurados"]], records: [["Ana Martins","Administrador","Ativo"],["Carlos Mendes","Comercial","Ativo"],["João Pereira","Motorista","Convite enviado"]] },
  settings: { id: "settings", eyebrow: "Configuração do tenant", title: "Configurações", description: "Gerencie dados da empresa, filiais, identidade visual, módulos e preferências.", primaryAction: "Salvar alterações", stats: [["Filiais","1","Matriz ativa"],["Módulos","8","7 habilitados"],["Domínio","1","Verificado"]], records: [["Identidade visual","Configurada","Fogueira Caminhões"],["Horário comercial","Configurado","Seg a sex"],["Políticas de acesso","Atualizadas","9 perfis"]] },
};
