import { Badge, buttonVariants } from "@roadcore/ui";
import Link from "next/link";
import { notFound } from "next/navigation";
import { sampleListings } from "@/features/marketplace/sample-listings";
import { VehicleCard } from "@/features/marketplace/components/vehicle-card";
const labels={available:"Disponível",reserved:"Reservado",sold:"Vendido"} as const;
const variants={available:"success",reserved:"warning",sold:"neutral"} as const;
const dots={available:"bg-emerald-500",reserved:"bg-amber-500",sold:"bg-neutral-500"} as const;
export default async function ListingPage({params}:{params:Promise<{tenant:string;id:string}>}){
 const {tenant,id}=await params;const item=sampleListings.find(x=>x.id===id);if(!item)notFound();const price=new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(item.priceInCents/100);const related=sampleListings.filter(x=>x.id!==id).slice(0,2);
 return <main className="flex-1 bg-surface"><div className="page-shell py-8 sm:py-12"><nav className="flex items-center gap-2 text-xs text-muted"><Link href={`/${tenant}`}>Início</Link><span>/</span><Link href={`/${tenant}/catalog`}>Estoque</Link><span>/</span><span className="text-foreground">{item.title}</span></nav><div className="mt-7 grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><div><div className="relative flex aspect-[16/10] items-center justify-center overflow-hidden rounded-3xl bg-gradient-to-br from-[#222225] to-[#0c0c0d] text-primary-600"><span className="absolute left-5 top-5 rounded-full bg-white px-3 py-1.5 text-[10px] font-black uppercase tracking-wider text-[#171717]">Seminovo certificado</span><svg viewBox="0 0 24 24" width="180" fill="none" stroke="currentColor" strokeWidth=".8"><path d="M3 16V7a1 1 0 0 1 1-1h9v10M3 16h1m0 0a2 2 0 1 0 4 0m-4 0h9m4 0h1a1 1 0 0 0 1-1v-3.5a1 1 0 0 0-.29-.7L20 9h-4v7m0 0a2 2 0 1 0 4 0m-4 0h-3"/></svg><div className="absolute bottom-5 right-5 rounded-full bg-black/50 px-3 py-1.5 text-[10px] text-white backdrop-blur">1 de 8 fotos</div></div><div className="mt-3 grid grid-cols-4 gap-3">{[1,2,3,4].map(x=><button key={x} aria-label={`Ver foto ${x}`} className={`aspect-[4/3] rounded-xl border-2 bg-neutral-200 ${x===1?"border-primary":"border-transparent"}`}/>)}</div></div><aside className="panel h-fit p-6 sm:p-8"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wider text-muted">Cód. RC-{2040+Number(id)}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{item.title}</h1></div><Badge variant={variants[item.status]}><span className={`h-1.5 w-1.5 rounded-full ${dots[item.status]}`}/>{labels[item.status]}</Badge></div><p className="mt-3 text-sm text-muted">2022 · Diesel · {item.location}</p><p className="mt-7 text-3xl font-bold">{price}</p><p className="mt-1 text-xs text-muted">Financie com entrada flexível e análise personalizada</p><div className="mt-7 grid grid-cols-2 gap-4 border-y py-5">{[["Quilometragem","348.000 km"],["Câmbio","Automatizado"],["Potência","540 cv"],["Tração","6x4"],["Implemento","Cavalo mecânico"],["Cor","Branco"]].map(([a,b])=><div key={a}><p className="text-[10px] font-semibold uppercase tracking-wider text-muted">{a}</p><p className="mt-1 text-sm font-semibold">{b}</p></div>)}</div><Link href={`/${tenant}/contact`} className={`${buttonVariants("primary")} mt-7 w-full !text-white`}>Tenho interesse neste veículo →</Link><Link href={`/${tenant}/financing`} className={`${buttonVariants("secondary")} mt-3 w-full`}>Simular financiamento</Link><div className="mt-5 flex justify-center gap-5 text-[10px] text-muted"><span>✓ Compra segura</span><span>✓ Suporte documental</span></div></aside></div>
 <div className="mt-14 grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><div className="panel p-7"><h2 className="text-xl font-semibold">Sobre este veículo</h2><p className="mt-4 leading-7 text-muted">Veículo selecionado pela nossa equipe, com configuração indicada para transporte rodoviário de médias e longas distâncias. Apresenta bom histórico de conservação e documentação regular para transferência.</p><h3 className="mt-8 font-semibold">Itens e diferenciais</h3><div className="mt-4 grid gap-3 sm:grid-cols-2">{["Ar-condicionado","Piloto automático","Freio motor","Cabine leito","Defletor de ar","Rodas de alumínio","Computador de bordo","Tanque suplementar"].map(x=><span key={x} className="rounded-lg bg-surface px-3 py-2 text-sm">✓ {x}</span>)}</div><p className="mt-6 text-xs leading-5 text-muted">As informações estão sujeitas a confirmação. Consulte o vendedor antes de concluir a negociação.</p></div><div className="panel p-7"><p className="text-xs font-bold uppercase tracking-wider text-primary">Vendedor verificado</p><h2 className="mt-3 text-xl font-semibold">Fogueira Caminhões</h2><p className="mt-2 text-sm text-muted">Curitiba, Paraná · Responde rapidamente</p><div className="mt-6 space-y-3 border-y py-5 text-sm"><div className="flex justify-between"><span className="text-muted">No portal desde</span><strong>2018</strong></div><div className="flex justify-between"><span className="text-muted">Veículos anunciados</span><strong>24</strong></div><div className="flex justify-between"><span className="text-muted">Avaliação</span><strong>4,9 / 5</strong></div></div><Link href={`/${tenant}/contact`} className="mt-6 inline-flex text-sm font-bold text-primary">Ver perfil da revenda →</Link></div></div>
 <section className="py-16"><div className="flex items-end justify-between"><div><p className="eyebrow">Você também pode gostar</p><h2 className="mt-2 text-3xl font-semibold">Veículos semelhantes</h2></div><Link href={`/${tenant}/catalog`} className="text-sm font-bold text-primary">Ver todo estoque →</Link></div><div className="mt-8 grid gap-6 md:grid-cols-2 lg:max-w-4xl">{related.map(x=><Link key={x.id} href={`/${tenant}/catalog/${x.id}`}><VehicleCard listing={x}/></Link>)}</div></section></div></main>
}
