/* eslint-disable @typescript-eslint/no-unused-vars */
import Link from "next/link";
import Image from "next/image";

export function MarketplaceExpansion({tenant}:{tenant:string}){
  const partners=[["DieselPro","Peças e motores"],["Rota Pneus","Pneus e recapagem"],["TruckCare","Oficinas credenciadas"],["Carga Segura","Seguros para pesados"],["Frota Capital","Crédito e refinanciamento"],["ViaTrack","Rastreamento"]];
  const articles=[["Guia de compra","O que avaliar antes de comprar um caminhão usado","7 min de leitura"],["Gestão de frota","Como calcular o custo real por quilômetro","5 min de leitura"],["Mercado","Os modelos mais procurados para transporte rodoviário","6 min de leitura"]];
  return <>
    <section className="page-shell py-20"><div className="relative min-h-[420px] overflow-hidden rounded-3xl bg-[#111112]"><Image src="/tenants/fogueiracaminhoes/vehicles/post-antigo/01.jpg" alt="Pátio da Fogueira Caminhões com veículos em exposição" fill sizes="100vw" className="object-cover opacity-60"/><div className="absolute inset-0 bg-gradient-to-r from-black/90 via-black/50 to-transparent"/><div className="relative flex min-h-[420px] max-w-xl flex-col justify-end p-8 text-white sm:p-12"><p className="text-xs font-bold uppercase tracking-[.2em] text-primary-400">Visite nosso pátio</p><h2 className="mt-4 text-4xl font-semibold tracking-tight">Negócio bom também se faz olhando de perto.</h2><p className="mt-4 leading-7 text-neutral-300">Conheça nosso estoque, converse com quem entende e encontre o caminhão certo para sua operação.</p><Link href={`/${tenant}/contact`} className="mt-7 inline-flex w-fit rounded-xl bg-primary px-6 py-3 text-sm font-bold text-white">Como chegar →</Link></div></div></section>
    <section className="border-y bg-white"><div className="page-shell py-16"><div className="rounded-3xl bg-gradient-to-r from-[#171719] to-[#29292c] p-7 text-white sm:p-10"><div className="grid items-center gap-8 lg:grid-cols-[1fr_auto]"><div><span className="rounded-full bg-white/10 px-3 py-1 text-[9px] font-bold uppercase tracking-[.18em] text-neutral-400">Conteúdo patrocinado</span><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-primary-400">Frota Capital</p><h2 className="mt-2 max-w-2xl text-3xl font-semibold tracking-tight">Troque de caminhão sem parar o seu negócio.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-neutral-400">Crédito para pesados, refinanciamento e capital para manutenção com análise especializada.</p></div><Link href={`/${tenant}/financing`} className="inline-flex min-h-12 items-center justify-center rounded-xl bg-primary px-6 text-sm font-bold text-white">Conhecer condições →</Link></div></div></div></section>

    <section className="page-shell py-20 sm:py-24"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Ecossistema da estrada</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.035em]">Tudo o que a sua operação precisa.</h2><p className="mt-3 max-w-2xl text-muted">Parceiros selecionados para cuidar do veículo, da carga e do caixa.</p></div><Link href={`/${tenant}/services`} className="text-sm font-bold text-primary">Explorar serviços →</Link></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{partners.map(([name,type],i)=><Link key={name} href={`/${tenant}/services`} className="group flex items-center gap-4 rounded-2xl border p-5 transition hover:-translate-y-0.5 hover:border-primary hover:shadow-lg"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#171717] text-xs font-black text-primary-400">{name.slice(0,2).toUpperCase()}</span><div><h3 className="font-semibold">{name}</h3><p className="mt-1 text-xs text-muted">{type}</p></div><span className="ml-auto text-muted transition group-hover:text-primary">↗</span></Link>)}</div><div className="mt-6 grid gap-4 md:grid-cols-3"><Link href={`/${tenant}/parts`} className="group rounded-2xl bg-primary-50 p-6"><span className="text-xs font-bold uppercase tracking-wider text-primary">Peças e acessórios</span><h3 className="mt-12 text-xl font-semibold">Encontre a peça certa para voltar à estrada.</h3><span className="mt-5 inline-flex text-sm font-bold">Ver fornecedores →</span></Link><Link href={`/${tenant}/dealers`} className="group rounded-2xl bg-[#171717] p-6 text-white"><span className="text-xs font-bold uppercase tracking-wider text-primary-400">Revendas verificadas</span><h3 className="mt-12 text-xl font-semibold">Compre de empresas que conhecem pesados.</h3><span className="mt-5 inline-flex text-sm font-bold">Conhecer revendas →</span></Link><Link href={`/${tenant}/advertise`} className="group rounded-2xl border-2 border-dashed border-neutral-300 p-6"><span className="text-xs font-bold uppercase tracking-wider text-muted">Espaço para sua marca</span><h3 className="mt-12 text-xl font-semibold">Fale com milhares de profissionais do setor.</h3><span className="mt-5 inline-flex text-sm font-bold text-primary">Anunciar na plataforma →</span></Link></div></section>

    <section className="bg-[#f5f5f3]"><div className="page-shell py-20 sm:py-24"><div className="flex items-end justify-between"><div><p className="eyebrow">Conteúdo RoadCore</p><h2 className="mt-3 text-4xl font-semibold tracking-[-.035em]">Informação para quem vive a estrada.</h2></div><Link href={`/${tenant}/blog`} className="hidden text-sm font-bold text-primary sm:block">Ver todos os conteúdos →</Link></div><div className="mt-10 grid gap-5 md:grid-cols-3">{articles.map(([tag,title,time],i)=><Link key={title} href={`/${tenant}/blog`} className="group overflow-hidden rounded-2xl bg-white shadow-sm"><div className={`flex aspect-[16/9] items-end p-5 ${i===1?"bg-[#202022]":"bg-gradient-to-br from-primary-800 to-[#171717]"}`}><span className="rounded-full bg-white/10 px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-white">{tag}</span></div><div className="p-6"><h3 className="text-lg font-semibold leading-6 transition group-hover:text-primary">{title}</h3><p className="mt-5 text-xs text-muted">{time} · RoadCore editorial</p></div></Link>)}</div></div></section>
  </>;
}
